# Importar configuración u otras utilidades
from .Constantes import   URL_INGRESO, URL_INGRESO, REGISTRO_FULL_NAME, EMAIL_USUARIO, CONTRASEÑA, NOMBRE_INCOMPLETO, CONTRASEÑA_ERRONEA, CONTRASEÑA_DIFERENTE, EMAIL_ERRONEO
